# fcitx-remote
# Autogenerated from man page /usr/share/man/man1/fcitx-remote.1.gz
complete -c fcitx-remote -s c -d 'inactivate input method'
complete -c fcitx-remote -s o -d 'activate input method'
complete -c fcitx-remote -s r -d 'reload fcitx config'
complete -c fcitx-remote -s t -d 'switch between active/inactive'
complete -c fcitx-remote -s s -d 'switch to the input method uniquely identified by imname'
complete -c fcitx-remote -s h -d 'display help and exit FILES fcitx will create socket at /tmp/fcitx-socket-<di…'

