# createPYMB
# Autogenerated from man page /usr/share/man/man1/createPYMB.1.gz
complete -c createPYMB -s b -d 'If not specified, it will read system default pybase. mb'
complete -c createPYMB -s f -d 'If not specified, it will read user default PhraseMBFile, which is ~/'
complete -c createPYMB -s s -d 'If specified, it will read PhraseMBFile as system format, otherwise will read…'
complete -c createPYMB -s h -d 'display help and exit'

