# fcitx
# Autogenerated from man page /usr/share/man/man1/fcitx.1.gz
complete -c fcitx -s r -d 'replace existing fcitx'
complete -c fcitx -s d -d 'run as daemon(default)'
complete -c fcitx -s D -d 'don\'t run as daemon'
complete -c fcitx -o 's[sleep' -d 'override delay start time in config file, 0 for immediate start'
complete -c fcitx -s u -l 'ui[ui' -d 'force to use specified user interface'
complete -c fcitx -l 'enable[addon' -d 'specify a comma separated list for addon that will override the enable option'
complete -c fcitx -l 'disable[addon' -d 'specify a comma separated list for addon that will explicitly disabled, prior…'
complete -c fcitx -s v -d 'display the version information and exit'
complete -c fcitx -s h -d 'display help and exit ENVIRONMENT'

